name: Lint, test and analyse

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run linting
        run: docker compose run --rm actions-tester composer test:lint
  testing:
    runs-on: ubuntu-latest
    name: Testing
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run testing
        run: docker compose run --rm actions-tester composer test:phpunit
        env:
          PHP_VERSION: ${{ matrix.php-version }}
  analysis:
    runs-on: ubuntu-latest
    name: Analysis
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run analysis
        run: docker compose run --rm actions-tester composer test:phpstan
  mess-detect:
    runs-on: ubuntu-latest
    name: Mess detector
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run mess detector
        run: docker compose run --rm actions-tester composer test:phpmd
  doc-check:
    runs-on: ubuntu-latest
    name: Documentation check
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run doc check
        run: docker compose run --rm actions-tester composer test:docs
